version: '3.4'

services:
  mariadb:
    image: ${DOCKER_REGISTRY-}mariadb
    container_name: chatpipoca
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "5000:80"
    restart: always
    environment:
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development

  database:
    image: mariadb:10.9.2
    container_name: mariadb
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: gq7cyo4e
      MARIADB_USER: docker_user
      MARIADB_PASSWORD: gq7cyo4e
      MARIADB_DATABASE: cp_data

volumes:
  db-volume:
