version: '3.4'

services:
  angular.docker:
    image: ${DOCKER_REGISTRY-}angulardocker
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - skip_client_build=true

  angular.app:
    image: ${DOCKER_REGISTRY-}angularapp
    build:
      context: .
      dockerfile: ClientApp/Dockerfile
    ports:
      - "4200:4200"
      - "48153:49153"
    volumes:
      - ./ClientApp:/app

  database:
    image: mariadb:10.8.3
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      vpcbr:
        ipv4_address: 172.29.0.3
    expose:
      - 3306
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: gq7cyo4e
      MARIADB_USER: docker_user
      MARIADB_PASSWORD: gq7cyo4e
      MARIADB_DATABASE: cp_data

  api:
    image: ${DOCKER_REGISTRY-}mariadb
    container_name: chatpipoca
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "5000:80"
    networks:
      vpcbr:
        ipv4_address: 172.29.0.5
    restart: always
    environment:
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  db-volume:

networks:
  vpcbr:
    ipam:
      config:
        - subnet: 172.29.0.0/24
