version: '3.4'

services:
  angular.docker:
    image: ${DOCKER_REGISTRY-}angulardocker
    build:
      context: .
      dockerfile: Dockerfile

  angular.app:
    image: ${DOCKER_REGISTRY-}angularapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - ./ClientApp:/app
